import { VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Annotator v0";
    min-width: 400px;
    min-height: 300px;

    in property <string> status-text: "Ready";

    VerticalBox {
        preferred-width: 1200px;
        preferred-height: 800px;
        Text {
            text: root.status-text;
            font-size: 24px;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
